/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    Color EnterColor = new Color(204,0,0);
    Color ExitColor = new Color(102,102,255);
    Color mouseEnterColor = new Color(0,0,0);
    Color mouseExitColor = new Color(51,51,51);
    DefaultTableModel model;
    public HomePage() {
        initComponents();
        setStudentDetailsToTable();
        setBookDetailsToTable();
        setDataToCards();
    }
    
    public void setStudentDetailsToTable() {
        
        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from student_details");
            
            while(rs.next()) {
                String studentId = rs.getString("student_id");
                String studentName = rs.getString("name");
                String course = rs.getString("course");
                String branch = rs.getString("branch");
                
                Object[] obj = {studentId, studentName, course, branch};
                model = (DefaultTableModel)tbl_studentsDetails.getModel();
                model.addRow(obj);
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // To set the book details into the table
    
    public void setBookDetailsToTable() {
        
        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from book_details");
            
            while(rs.next()) {
                String bookId = rs.getString("book_id");
                String bookName = rs.getString("book_name");
                String author = rs.getString("author");
                int quantity = rs.getInt("quantity");
                
                Object[] obj = {bookId, bookName, author, quantity};
                model = (DefaultTableModel)tbl_bookDetails.getModel();
                model.addRow(obj);
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // method to set the counters
    
    public void setDataToCards() {
        Statement st = null;
        ResultSet rs = null;
        int count = 0;
        
        long l = System.currentTimeMillis();
        Date todaysDate = new Date(l);
        
        try {
            Connection con = DBConnection.getConnection();
            st = con.createStatement();
            rs = st.executeQuery("select * from book_details");
            while(rs.next()) count++;
            lbl_bookCount.setText(Integer.toString(count));
            
            rs = st.executeQuery("select * from student_details");
            count = 0;
            while(rs.next()) count++;
            lbl_studentCount.setText(Integer.toString(count));
            
            rs = st.executeQuery("select * from issue_book_details "
                    + "where status = '"+"pending"+"'");
            count = 0;
            while(rs.next()) count++;
            lbl_issuedBookCount.setText(Integer.toString(count));
            
            rs = st.executeQuery("select * from issue_book_details "
                    + "where due_date < '"+todaysDate+"' "
                    + "and status = '"+"pending"+"'");
            count = 0;
            while(rs.next()) count++;
            lbl_defaulterCount.setText(Integer.toString(count));
        }catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        closePanel = new javax.swing.JPanel();
        closeBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        manageBooksPanel = new javax.swing.JPanel();
        manageBooksLabel = new javax.swing.JLabel();
        manageStudentsPanel = new javax.swing.JPanel();
        manageStudentsLabel = new javax.swing.JLabel();
        issueBookPanel = new javax.swing.JPanel();
        issueBookLabel = new javax.swing.JLabel();
        returnBookPanel = new javax.swing.JPanel();
        returnBookLabel = new javax.swing.JLabel();
        viewRecordsPanel = new javax.swing.JPanel();
        viewRecordsLabel = new javax.swing.JLabel();
        viewIssuedBooksPanel = new javax.swing.JPanel();
        viewIssuedBooksLabel = new javax.swing.JLabel();
        defaulterListPanel = new javax.swing.JPanel();
        defaulterListLabel = new javax.swing.JLabel();
        logOutPanel = new javax.swing.JPanel();
        logOutLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbl_bookCount = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lbl_studentCount = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lbl_issuedBookCount = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        lbl_defaulterCount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_studentsDetails = new rojeru_san.complementos.RSTableMetro();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bookDetails = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 5, 5, 40));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Library Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 380, -1));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel3.setText("Welcome, Admin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 200, -1));

        closePanel.setBackground(new java.awt.Color(102, 102, 255));
        closePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("X");
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        closePanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        jPanel1.add(closePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel4.setText("  Home Page");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 60));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        jLabel5.setText("  LMS Dashboard");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 60));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Features");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, 30));

        manageBooksPanel.setBackground(new java.awt.Color(51, 51, 51));
        manageBooksPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageBooksLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        manageBooksLabel.setForeground(new java.awt.Color(153, 153, 153));
        manageBooksLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        manageBooksLabel.setText("  Manage Books");
        manageBooksLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageBooksLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageBooksLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageBooksLabelMouseExited(evt);
            }
        });
        manageBooksPanel.add(manageBooksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel3.add(manageBooksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 340, 60));

        manageStudentsPanel.setBackground(new java.awt.Color(51, 51, 51));
        manageStudentsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageStudentsLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        manageStudentsLabel.setForeground(new java.awt.Color(153, 153, 153));
        manageStudentsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        manageStudentsLabel.setText("  Manage Students");
        manageStudentsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageStudentsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageStudentsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageStudentsLabelMouseExited(evt);
            }
        });
        manageStudentsPanel.add(manageStudentsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 30));

        jPanel3.add(manageStudentsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 340, 60));

        issueBookPanel.setBackground(new java.awt.Color(51, 51, 51));
        issueBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issueBookLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        issueBookLabel.setForeground(new java.awt.Color(153, 153, 153));
        issueBookLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        issueBookLabel.setText("  Issue Book");
        issueBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueBookLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issueBookLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issueBookLabelMouseExited(evt);
            }
        });
        issueBookPanel.add(issueBookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 30));

        jPanel3.add(issueBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 340, 60));

        returnBookPanel.setBackground(new java.awt.Color(51, 51, 51));
        returnBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnBookLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        returnBookLabel.setForeground(new java.awt.Color(153, 153, 153));
        returnBookLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        returnBookLabel.setText("  Return Book");
        returnBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBookLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnBookLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnBookLabelMouseExited(evt);
            }
        });
        returnBookPanel.add(returnBookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 30));

        jPanel3.add(returnBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 340, 60));

        viewRecordsPanel.setBackground(new java.awt.Color(51, 51, 51));
        viewRecordsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewRecordsLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        viewRecordsLabel.setForeground(new java.awt.Color(153, 153, 153));
        viewRecordsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        viewRecordsLabel.setText("  View Records");
        viewRecordsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRecordsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewRecordsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewRecordsLabelMouseExited(evt);
            }
        });
        viewRecordsPanel.add(viewRecordsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 30));

        jPanel3.add(viewRecordsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 340, 60));

        viewIssuedBooksPanel.setBackground(new java.awt.Color(51, 51, 51));
        viewIssuedBooksPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewIssuedBooksLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        viewIssuedBooksLabel.setForeground(new java.awt.Color(153, 153, 153));
        viewIssuedBooksLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
        viewIssuedBooksLabel.setText("  View Issued Books");
        viewIssuedBooksLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewIssuedBooksLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewIssuedBooksLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewIssuedBooksLabelMouseExited(evt);
            }
        });
        viewIssuedBooksPanel.add(viewIssuedBooksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 30));

        jPanel3.add(viewIssuedBooksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 340, 60));

        defaulterListPanel.setBackground(new java.awt.Color(51, 51, 51));
        defaulterListPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        defaulterListLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        defaulterListLabel.setForeground(new java.awt.Color(153, 153, 153));
        defaulterListLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        defaulterListLabel.setText("  Defaulter List");
        defaulterListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defaulterListLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                defaulterListLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                defaulterListLabelMouseExited(evt);
            }
        });
        defaulterListPanel.add(defaulterListLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 30));

        jPanel3.add(defaulterListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 340, 60));

        logOutPanel.setBackground(new java.awt.Color(102, 102, 255));
        logOutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logOutLabel.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        logOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        logOutLabel.setText("  Logout");
        logOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutLabelMouseExited(evt);
            }
        });
        logOutPanel.add(logOutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 30));

        jPanel3.add(logOutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 340, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 830));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_bookCount.setFont(new java.awt.Font("Century Schoolbook", 1, 50)); // NOI18N
        lbl_bookCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lbl_bookCount.setText("10");
        jPanel7.add(lbl_bookCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 51, -1, -1));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 200, 150));

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Students Details");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("No. of Students");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 160, -1));

        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 102, 255)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_studentCount.setFont(new java.awt.Font("Century Schoolbook", 1, 50)); // NOI18N
        lbl_studentCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        lbl_studentCount.setText("10");
        jPanel16.add(lbl_studentCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 53, -1, -1));

        jPanel5.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 200, 150));

        jLabel19.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Issued Books");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 140, -1));

        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_issuedBookCount.setFont(new java.awt.Font("Century Schoolbook", 1, 50)); // NOI18N
        lbl_issuedBookCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        lbl_issuedBookCount.setText("10");
        jPanel17.add(lbl_issuedBookCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 51, -1, -1));

        jPanel5.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 200, 150));

        jLabel22.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Defaulter List");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 150, -1));

        jPanel18.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 102, 255)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_defaulterCount.setFont(new java.awt.Font("Century Schoolbook", 1, 50)); // NOI18N
        lbl_defaulterCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lbl_defaulterCount.setText("10");
        jPanel18.add(lbl_defaulterCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 51, -1, -1));

        jPanel5.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 200, 150));

        tbl_studentsDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Course", "Branch"
            }
        ));
        tbl_studentsDetails.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_studentsDetails.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbl_studentsDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_studentsDetails.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tbl_studentsDetails.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        tbl_studentsDetails.setFuenteFilas(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        tbl_studentsDetails.setFuenteFilasSelect(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        tbl_studentsDetails.setFuenteHead(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        tbl_studentsDetails.setRowHeight(30);
        tbl_studentsDetails.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tbl_studentsDetails);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 570, 240));

        jLabel23.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("No. of Books");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Book Details");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        tbl_bookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Name", "Author", "Quantity"
            }
        ));
        tbl_bookDetails.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_bookDetails.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbl_bookDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_bookDetails.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tbl_bookDetails.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        tbl_bookDetails.setFuenteFilas(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        tbl_bookDetails.setFuenteFilasSelect(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        tbl_bookDetails.setFuenteHead(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        tbl_bookDetails.setRowHeight(30);
        jScrollPane2.setViewportView(tbl_bookDetails);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 570, 240));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 1200, 830));

        setSize(new java.awt.Dimension(1540, 880));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manageBooksLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBooksLabelMouseClicked
        ManageBooks books = new ManageBooks();
        books.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageBooksLabelMouseClicked

    private void manageBooksLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBooksLabelMouseEntered
        manageBooksPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_manageBooksLabelMouseEntered

    private void manageBooksLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBooksLabelMouseExited
        manageBooksPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_manageBooksLabelMouseExited

    private void manageStudentsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentsLabelMouseEntered
        manageStudentsPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_manageStudentsLabelMouseEntered

    private void manageStudentsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentsLabelMouseExited
        manageStudentsPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_manageStudentsLabelMouseExited

    private void issueBookLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookLabelMouseEntered
        issueBookPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_issueBookLabelMouseEntered

    private void issueBookLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookLabelMouseExited
        issueBookPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_issueBookLabelMouseExited

    private void returnBookLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookLabelMouseEntered
        returnBookPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_returnBookLabelMouseEntered

    private void returnBookLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookLabelMouseExited
        returnBookPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_returnBookLabelMouseExited

    private void viewRecordsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecordsLabelMouseEntered
        viewRecordsPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_viewRecordsLabelMouseEntered

    private void viewRecordsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecordsLabelMouseExited
        viewRecordsPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_viewRecordsLabelMouseExited

    private void viewIssuedBooksLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewIssuedBooksLabelMouseEntered
        viewIssuedBooksPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_viewIssuedBooksLabelMouseEntered

    private void viewIssuedBooksLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewIssuedBooksLabelMouseExited
        viewIssuedBooksPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_viewIssuedBooksLabelMouseExited

    private void defaulterListLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterListLabelMouseEntered
        defaulterListPanel.setBackground(mouseEnterColor);
    }//GEN-LAST:event_defaulterListLabelMouseEntered

    private void defaulterListLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterListLabelMouseExited
        defaulterListPanel.setBackground(mouseExitColor);
    }//GEN-LAST:event_defaulterListLabelMouseExited

    private void manageStudentsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentsLabelMouseClicked
        ManageStudents students = new ManageStudents();
        students.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageStudentsLabelMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
       closePanel.setBackground(EnterColor);
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        closePanel.setBackground(ExitColor);
    }//GEN-LAST:event_closeBtnMouseExited

    private void returnBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookLabelMouseClicked
        ReturnBook retBook = new ReturnBook();
        retBook.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnBookLabelMouseClicked

    private void issueBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookLabelMouseClicked
        IssueBook books = new IssueBook();
        books.setVisible(true);
        dispose();
    }//GEN-LAST:event_issueBookLabelMouseClicked

    private void viewRecordsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecordsLabelMouseClicked
        ViewAllRecord record = new ViewAllRecord();
        record.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewRecordsLabelMouseClicked

    private void viewIssuedBooksLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewIssuedBooksLabelMouseClicked
        IssueBookDetails issue = new IssueBookDetails();
        issue.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewIssuedBooksLabelMouseClicked

    private void defaulterListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterListLabelMouseClicked
        DefaulterList defaulterList = new DefaulterList();
        defaulterList.setVisible(true);
        dispose();
    }//GEN-LAST:event_defaulterListLabelMouseClicked

    private void logOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseClicked
        LoginPage login = new LoginPage();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutLabelMouseClicked

    private void logOutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseEntered
        logOutPanel.setBackground(new Color(51,51,255));
    }//GEN-LAST:event_logOutLabelMouseEntered

    private void logOutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseExited
        logOutPanel.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_logOutLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeBtn;
    private javax.swing.JPanel closePanel;
    private javax.swing.JLabel defaulterListLabel;
    private javax.swing.JPanel defaulterListPanel;
    private javax.swing.JLabel issueBookLabel;
    private javax.swing.JPanel issueBookPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_bookCount;
    private javax.swing.JLabel lbl_defaulterCount;
    private javax.swing.JLabel lbl_issuedBookCount;
    private javax.swing.JLabel lbl_studentCount;
    private javax.swing.JLabel logOutLabel;
    private javax.swing.JPanel logOutPanel;
    private javax.swing.JLabel manageBooksLabel;
    private javax.swing.JPanel manageBooksPanel;
    private javax.swing.JLabel manageStudentsLabel;
    private javax.swing.JPanel manageStudentsPanel;
    private javax.swing.JLabel returnBookLabel;
    private javax.swing.JPanel returnBookPanel;
    private rojeru_san.complementos.RSTableMetro tbl_bookDetails;
    private rojeru_san.complementos.RSTableMetro tbl_studentsDetails;
    private javax.swing.JLabel viewIssuedBooksLabel;
    private javax.swing.JPanel viewIssuedBooksPanel;
    private javax.swing.JLabel viewRecordsLabel;
    private javax.swing.JPanel viewRecordsPanel;
    // End of variables declaration//GEN-END:variables
}
